### ISSUE TITLE
Templates are broken empty <body> in client HTML

### ISSUE THREAD

**Issue by ghost** [iron-meteor/iron-layout#11]
I have had this problem since updating a day ago. No templates work I have tried my code and the microscope git code only the head has anything in it the body is empty on client.  I would go back to a older version but I was dumb and tried deleting and reinstalling meteor so I can't please fix this Thanks
I just closed it because it randomly stopped but it randomly just started aging.

**Comment by deanp70** [comment]
Im working on a project in meteor. runs fine in chrome but when i open it in firefox, the only thing in the body are the default meteor script. no other elements appear. this same project (without any code changes) has run on firefox a couple of days ago. now no project (including the defaul project made by meteor) can be viewed. would love some help
